apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
    - name: secret-demo
      image: alpine:latest
      command: ["sh", "-c", "sleep 3600"]

      env:
        - name: APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: username

        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
